services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      
      FIRESTORE_EMULATOR_HOST: firestore:8080
      FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
      
      MINIO_URL: http://storage:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      QR_STORAGE_BUCKET: qr-codes
      
      FIREBASE_CREDENTIALS: ${FIREBASE_CREDENTIALS}
    depends_on:
      firestore:
        condition: service_started
      storage:
       condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_healthy

  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    container_name: firestore
    ports:
      - "8082:8080"
    command: ["gcloud", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
    volumes:
      - firestore-data:/data

  storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: storage
    ports:
      - "8083:9000"
      - "8084:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 3
    
volumes:
  minio-data:
  firestore-data:
